export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
            <title>My App</title>
      </head>
      {children}
    </html>
  )
}


function Navbar(){
    return(
        <nav className="nav-bar">
            <ol>
                <li><a href="#">Home</a></li>
                <li><a href="#">News</a></li>
                <li><a href="#">Sign Up</a></li>
            </ol>
        </nav>       
    )
}